In [1]:
import numpy as np
import numpy.f2py as f2py
import rovibpy
import os
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (12,8)
import plotly.express as px


In [2]:
print(rovibpy.rovib.__doc__)

rovib_wavefunctions : 'd'-array(-1,-1,-1), not allocated
rovib_energies : 'd'-array(-1,-1), not allocated
use_rovib(rmin,rmax,step,mass,nmax,vmax)

Wrapper for ``use_rovib``.

Parameters
----------
rmin : input float
rmax : input float
step : input float
mass : in/output rank-0 array(float,'d')
nmax : input float
vmax : input int
hamiltonian = dvr_radial(m,step,grid,potential,[ngp])

Wrapper for ``dvr_radial``.

Parameters
----------
m : input float
step : input float
grid : input rank-1 array('d') with bounds (ngp)
potential : input rank-1 array('d') with bounds (ngp)

Other Parameters
----------------
ngp : input int, optional
    Default: len(grid)

Returns
-------
hamiltonian : rank-2 array('d') with bounds (ngp,ngp)
orthonormal_check(indexa,indexb,grid,eigenvectors,[ngp])

Wrapper for ``orthonormal_check``.

Parameters
----------
indexa : input int
indexb : input int
grid : input rank-1 array('d') with bounds (ngp)
eigenvectors : input rank-2 array('d') with bounds (ngp,ngp)

Ot

In [3]:
input_data = np.loadtxt('LiCs_PEC_numpy.in')#, dtype={'names':('r','Vr'), 'formats':('%1.15d', '%1.15d')})
input_data

array([[ 4.00000000e+00,  1.69029636e+04],
       [ 4.02092646e+00,  1.61678747e+04],
       [ 4.04185292e+00,  1.54448587e+04],
       ...,
       [ 4.34836931e+02, -5.46155976e-08],
       [ 4.75139306e+02, -7.84931997e-08],
       [ 5.15441682e+02, -5.33131039e-08]])

In [4]:
r = input_data[:,0]
Vr = input_data[:,1]

fig = px.line(x=r, y=Vr, labels={'x':'r', 'y':'V(r)'})
fig.update_layout(
    autosize=False,
    width=800,
    height=500)
fig.show()


In [5]:
m = 1.
step = 5.
grid = input_data[:,0]
potential = input_data[:,1]
hamiltonian = np.zeros((input_data[:,0].shape[0],input_data[:,0].shape[0]), order='F')
ngp = input_data[:,0].shape[0]
hamiltonian

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
hamiltonian = rovibpy.rovib.dvr_radial(m,step,grid,potential,input_data[:,0].shape[0])
hamiltonian

array([[ 1.69030194e+04, -3.55555556e-02,  7.50000000e-03, ...,
         3.02186978e-10, -3.01069145e-10,  2.99956820e-10],
       [-3.55555556e-02,  1.61679380e+04, -3.84000000e-02, ...,
        -6.04379496e-10,  6.02143797e-10, -5.99919113e-10],
       [ 7.50000000e-03, -3.84000000e-02,  1.54449234e+04, ...,
         9.06583096e-10, -9.03229463e-10,  8.99892351e-10],
       ...,
       [ 3.02186978e-10, -6.04379496e-10,  9.06583096e-10, ...,
         6.57972928e-02, -3.99999847e-02,  9.99998476e-03],
       [-3.01069145e-10,  6.02143797e-10, -9.03229463e-10, ...,
        -3.99999847e-02,  6.57972689e-02, -3.99999848e-02],
       [ 2.99956820e-10, -5.99919113e-10,  8.99892351e-10, ...,
         9.99998476e-03, -3.99999848e-02,  6.57972942e-02]])

In [7]:
print(hamiltonian.shape)
diagonal = np.diagonal(hamiltonian)
print(diagonal.shape)
print(diagonal)

(811, 811)
(811,)
[ 1.69030194e+04  1.61679380e+04  1.54449234e+04  1.48109965e+04
  1.41857609e+04  1.35560582e+04  1.29478668e+04  1.23679847e+04
  1.18129072e+04  1.12812018e+04  1.07723408e+04  1.02846938e+04
  9.81617677e+03  9.36493848e+03  8.92925842e+03  8.50763193e+03
  8.09878219e+03  7.70221736e+03  7.31767642e+03  6.94478122e+03
  6.58311869e+03  6.23227380e+03  5.89187089e+03  5.56168624e+03
  5.24159683e+03  4.93170068e+03  4.63212229e+03  4.34292163e+03
  4.06417961e+03  3.79606963e+03  3.53861482e+03  3.29141858e+03
  3.05388961e+03  2.82514117e+03  2.60428490e+03  2.39051369e+03
  2.18298903e+03  1.98079747e+03  1.78324941e+03  1.59005350e+03
  1.40104573e+03  1.21619924e+03  1.03547464e+03  8.58798339e+02
  6.86104832e+02  5.17340266e+02  3.52384341e+02  1.91037345e+02
  3.30897285e+01 -1.21673734e+02 -2.73468189e+02 -4.22508206e+02
 -5.69004084e+02 -7.13154756e+02 -8.55035649e+02 -9.94622024e+02
 -1.13189097e+03 -1.26682290e+03 -1.39939571e+03 -1.52958607e+03
 -1.657

In [8]:
fig = px.line(x=r, y=diagonal, labels={'x':'r', 'y':'V(r)'})
fig.update_layout(
    autosize=False,
    width=800,
    height=500)
fig.show()

In [9]:
# import numpy as np
# import os
# os.system('rm rovib2')
# os.system('gfortran -w unit_conversion.f90 spline.f90 integration_double.f90 rovib.f90 -o rovib2 -llapack -lblas')
# os.system('./rovib2 > file')
# fortran_data = np.loadtxt('file')

In [10]:
rmin = 4.
rmax = 50.
step = 0.01
mass = 6.664204432
NMax = 0
vmax = 16
# r y Vr son del archivo *_PEC_numpy.in

rovibpy.rovib.use_rovib(rmin,rmax,step,mass,NMax,vmax)

 Setting parameters for LiCs
 Reading potential energy curve
 Construction of the DVR Hamiltonian
 Begin DVR
 End DVR


In [23]:
wavefunc = rovibpy.rovib.rovib_wavefunctions[0]
wavefunc

4601


In [12]:
energies = rovibpy.rovib.rovib_energies[0]
energies

array([-0.0263509 , -0.02551801, -0.0246943 , -0.02387984, -0.02307467,
       -0.02227883, -0.02149243, -0.02071559, -0.01994844, -0.01919107,
       -0.01844359, -0.01770608, -0.01697865, -0.01626142, -0.01555455,
       -0.01485819, -0.01417253])

In [13]:
print(wavefunc.shape)
print(wavefunc[0].shape)
print(energies.shape)

(4601, 17)
(17,)
(17,)


In [26]:
import pandas as pd
df = pd.DataFrame(data=wavefunc)

In [28]:
# columna 0 -> v=0
df[0]

0       1.070985e-17
1       2.674158e-17
2       4.550496e-17
3       5.936937e-17
4       6.238548e-17
            ...     
4596    1.213105e-17
4597    2.345644e-17
4598    9.576639e-18
4599    1.372622e-17
4600    2.456478e-19
Name: 0, Length: 4601, dtype: float64

In [20]:
wavefunc[0]

array([ 1.07098537e-17,  1.95087313e-17, -1.03406587e-16, -4.57877036e-17,
       -3.20928053e-17, -2.23307268e-16,  2.87071851e-17,  7.73952246e-18,
       -8.80142675e-17,  1.21039402e-16, -7.21034966e-17, -2.74070612e-16,
       -8.95545507e-18, -6.44337266e-17,  3.76206513e-16, -4.52178510e-17,
        4.17965568e-17])

In [36]:
X = np.linspace(4, 50, 4601)
fig = px.line(x=X, y=df[3], labels={'x':'E', 'y':'psi(E)'})
fig.update_layout(
    autosize=False,
    width=800,
    height=500)
fig.show()